### ISSUE TITLE
`widgetMaker` ignores custom drawing function if no custom functions are present

### ISSUE THREAD

**Issue by bitonic** [deech/fltkhs#39]
```
widgetMaker rectangle _label' draw' customFuncs' new' newWithLabel' newWithCustomFuncs' newWithCustomFuncsLabel' =
    let (x_pos, y_pos, width, height) = fromRectangle rectangle
    in case (_label', customFuncs') of
        (Nothing,Nothing) -> new' x_pos y_pos width height >>= toRef
        ((Just l), Nothing) -> newWithLabel' x_pos y_pos width height l >>= toRef
        ((Just l), (Just fs)) -> do
          ptr <- customWidgetFunctionStruct draw' fs
          newWithCustomFuncsLabel' x_pos y_pos width height l (castPtr ptr) >>= toRef
        (Nothing, (Just fs)) -> do
          ptr <- customWidgetFunctionStruct draw' fs
          newWithCustomFuncs' x_pos y_pos width height (castPtr ptr) >>= toRef
```

In the first two cases of the `case` the `draw'` function is ignored.

**Comment by deech** [comment]
Yes, that is confusing. That function wasn't meant to be used by the end-user. It is used internally by other widgets to draw themselves but exposed because those widgets live in their own modules and there's no `package private` concept in Haskell. 

Instead please use `widgetCustom` in the same module. It takes a mandatory `CustomWidgetFuncs` argument for which you can just pass `defaultCustomWidgetFuncs` if you don't have any.

Sorry for the confusion. I'll update the documentation advising the user to steer clear and for the next release I'll move it to it's own un-exposed module. Thanks!

**Comment by bitonic** [comment]
Well, the problem is that this issue is reflected in functions that _are_ meant to be used, such as `boxCustom`. This is how I stumbled upon it.

**Comment by deech** [comment]
Oh boy, you're right. I'll fix it ASAP.

**Comment by bitonic** [comment]
Thanks! And thanks for the awesome library -- finally something simple and cross platform that works with no hassle.

**Comment by deech** [comment]
If it's holding you up, you to get around it you should be able to pass `Just(defaultCustomWidgetFuncs)` to `boxCustom` to get it to use the `draw` function.

**Comment by bitonic** [comment]
Yep, that's what I'm doing already.

**Comment by deech** [comment]
This is now fixed in HEAD (along with some other doc updates). Can you use this or would you rather wait till it's on Hackage?

**Comment by bitonic** [comment]
I'm OK using the workaround for now, thank you so much for the prompt
response!

**Comment by deech** [comment]
Closing this issue since it is fixed here and on Hackage (http://hackage.haskell.org/package/fltkhs-0.4.1.0).
